services:
  db:
    image: postgres:16
    container_name: vetcare_db
    restart: always
    environment:
      POSTGRES_DB: vetcare_db
      POSTGRES_USER: vetcare_user
      POSTGRES_PASSWORD: vetcare_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: