# Generated by Django 6.0.6 on 2026-06-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
