# Generated by Django 6.0.6 on 2026-06-28 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atenciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamentos', models.CharField(max_length=100)),
                ('indicaciones', models.TextField()),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atenciones.atencion')),
            ],
        ),
    ]
