# Generated by Django 6.0.6 on 2026-07-14 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atenciones', '0001_initial'),
        ('citas', '0002_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='diagnostico',
            field=models.TextField(default='Sin diagnóstico registrado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atencion',
            name='sintomas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atencion', to='citas.cita'),
        ),
    ]
