# Generated by Django 6.0.6 on 2026-06-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('mascotas', '0002_alter_mascota_peso'),
        ('veterinarios', '0002_alter_veterinario_correo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('veterinario', 'fecha', 'hora'), name='unique_veterinario_fecha_hora'),
        ),
    ]
